// Generated by splitting the original interior.js — geometry is unchanged.
import { rng } from '../textures.js';

export function createDoors(ctx) {
  const { house, S, makeGroup } = ctx;

  // =================================================================
  // INTERNAL DOORS: jambs, architraves, leaves, handles
  // =================================================================
  function buildDoors() {
    const g = makeGroup('doors');
    const style = S.doors?.style;
    const lever = S.handles?.lever;
    const H = 2.34;
    for (const op of house.plan.openings) {
      const { axis, pos, a, b, half } = op;
      if (b - a < 0.3) continue;
      const at = op.swingLeft ? b - 0.075 : a + 0.075;
      if (axis === 'x') {
        // the wall runs along X at z = pos
        g.box('woodwork', a - 0.022, 0, pos - half - 0.006, a, H + 0.022, pos + half + 0.006);
        g.box('woodwork', b, 0, pos - half - 0.006, b + 0.022, H + 0.022, pos + half + 0.006);
        g.box('woodwork', a - 0.022, H, pos - half - 0.006, b + 0.022, H + 0.022, pos + half + 0.006);
        for (const s of [-1, 1]) {
          const d = s * (half + 0.006);
          g.box('woodwork', a - 0.07, 0, pos + d, a - 0.022, H + 0.07, pos + d + s * 0.012);
          g.box('woodwork', b + 0.022, 0, pos + d, b + 0.07, H + 0.07, pos + d + s * 0.012);
          g.box('woodwork', a - 0.07, H + 0.022, pos + d, b + 0.07, H + 0.07, pos + d + s * 0.012);
        }
        leaf(g, a + 0.012, b - 0.012, pos, 'x', style, H);
        handle(g, 'x', pos, at);
      } else {
        g.box('woodwork', pos - half - 0.006, 0, a - 0.022, pos + half + 0.006, H + 0.022, a);
        g.box('woodwork', pos - half - 0.006, 0, b, pos + half + 0.006, H + 0.022, b + 0.022);
        g.box('woodwork', pos - half - 0.006, H, a - 0.022, pos + half + 0.006, H + 0.022, b + 0.022);
        for (const s of [-1, 1]) {
          const d = s * (half + 0.006);
          g.box('woodwork', pos + d, 0, a - 0.07, pos + d + s * 0.012, H + 0.07, a - 0.022);
          g.box('woodwork', pos + d, 0, b + 0.022, pos + d + s * 0.012, H + 0.07, b + 0.07);
          g.box('woodwork', pos + d, H + 0.022, a - 0.07, pos + d + s * 0.012, H + 0.07, b + 0.07);
        }
        leaf(g, a + 0.012, b - 0.012, pos, 'z', style, H);
        handle(g, 'z', pos, at);
      }
    }
    g.finish();

    function leaf(gr, s0, s1, pos, axis, st, h) {
      const t = 0.019;
      const put = (u0, v0, u1, v1, d0, d1, key = 'woodwork') => {
        if (axis === 'x') gr.box(key, u0, v0, pos + d0, u1, v1, pos + d1);
        else gr.box(key, pos + d0, v0, u0, pos + d1, v1, u1);
      };
      const p = st?.panels || 'flush';
      put(s0, 0.02, s1, h, -t, t);
      if (p === 'groove' || p === 'barn') {
        for (let u = s0 + 0.09; u < s1 - 0.06; u += 0.115) put(u, 0.06, u + 0.012, h - 0.06, -t - 0.005, -t);
      } else if (p === 'panel' || p === 'shaker' || p === 'settler') {
        const rows = p === 'shaker' ? 2 : 3;
        const inner = h - 0.26;
        for (let i = 0; i < rows; i++) {
          const v0 = 0.14 + i * (inner / rows);
          const v1 = v0 + inner / rows - 0.1;
          put(s0 + 0.11, v0, s1 - 0.11, v1, -t - 0.006, -t);
          put(s0 + 0.11, v0, s1 - 0.11, v1, t, t + 0.006);
        }
      } else if (p === 'glazed') {
        put(s0 + 0.09, 0.2, s1 - 0.09, h - 0.12, -t - 0.001, t + 0.001, 'glassFrosted');
      }
      if (st?.glass && p !== 'glazed') put(s0 + 0.13, h * 0.5, s1 - 0.13, h - 0.14, -t - 0.001, t + 0.001, 'glassFrosted');
    }

    function handle(gr, axis, pos, at) {
      const y = 1.02;
      const square = ['dh-sierra', 'dh-rivera', 'dh-alba'].includes(lever?.id);
      const r = square ? 0.032 : 0.027;
      for (const s of [-1, 1]) {
        const d = s * 0.026;
        if (axis === 'x') {
          gr.box('handle', at - r, y - r, pos + d, at + r, y + r, pos + d * 1.35);
          gr.box('handle', at - 0.011, y - 0.011, pos + d * 1.35, at + 0.09, y + 0.011, pos + d * 2.8);
        } else {
          gr.box('handle', pos + d, y - r, at - r, pos + d * 1.35, y + r, at + r);
          gr.box('handle', pos + d * 1.35, y - 0.011, at - 0.011, pos + d * 2.8, y + 0.011, at + 0.09);
        }
      }
    }
  }

  // =================================================================
  // ROBES: sliding doors (one panel slid open) + fit-out
  // =================================================================
  function buildRobes() {
    const g = makeGroup('robes');
    const doorKey = S.robes?.door?.style === 'painted' ? 'woodwork' : 'robeDoor';
    const fitout = S.robes?.fitout?.fitout || 'standard';
    const H = 2.31;
    for (const r of house.plan.robes) {
      if (r.faceDir === 'x') {
        const x = r.x0;
        const mid = (r.z0 + r.z1) / 2;
        g.box(doorKey, x + 0.012, 0.03, r.z0, x + 0.032, H, mid + 0.02);
        g.box('handle', x + 0.032, 0.95, mid - 0.02, x + 0.04, 1.2, mid);
        g.box(doorKey, x + 0.038, 0.03, mid + 0.28, x + 0.058, H, r.z1);
        g.box('handle', x + 0.058, 0.95, mid + 0.28, x + 0.066, 1.2, mid + 0.3);
        fit(g, x - 0.56, r.z0 + 0.02, x - 0.02, r.z1 - 0.02, fitout, 'x');
      } else {
        const z = r.z0;
        const mid = (r.x0 + r.x1) / 2;
        g.box(doorKey, r.x0, 0.03, z + 0.012, mid + 0.02, H, z + 0.032);
        g.box('handle', mid - 0.02, 0.95, z + 0.032, mid, 1.2, z + 0.04);
        g.box(doorKey, mid + 0.28, 0.03, z + 0.038, r.x1, H, z + 0.058);
        g.box('handle', mid + 0.28, 0.95, z + 0.058, mid + 0.3, 1.2, z + 0.066);
        fit(g, r.x0 + 0.02, z - 0.56, r.x1 - 0.02, z - 0.02, fitout, 'z');
      }
    }
    g.finish();

    function fit(gr, x0, z0, x1, z1, kind, dir) {
      const mat = kind === 'custom' ? 'oakDark' : 'mel';
      gr.box(mat, x0, 1.78, z0, x1, 1.81, z1); // top shelf
      if (dir === 'x') gr.box('handle', x0 + 0.24, 1.66, z0, x0 + 0.268, 1.688, z1);
      else gr.box('handle', x0, 1.66, z0 + 0.24, x1, 1.688, z0 + 0.268);
      if (kind !== 'standard') {
        const cx = (x0 + x1) / 2;
        const cz = (z0 + z1) / 2;
        if (dir === 'x') {
          gr.box(mat, x0, 0.02, cz - 0.3, x1, 1.78, cz - 0.282);
          gr.box(mat, x0, 0.02, cz + 0.282, x1, 1.78, cz + 0.3);
          for (let y = 0.34; y < 1.72; y += 0.33) gr.box(mat, x0, y, cz - 0.282, x1, y + 0.018, cz + 0.282);
        } else {
          gr.box(mat, cx - 0.3, 0.02, z0, cx - 0.282, 1.78, z1);
          gr.box(mat, cx + 0.282, 0.02, z0, cx + 0.3, 1.78, z1);
          for (let y = 0.34; y < 1.72; y += 0.33) gr.box(mat, cx - 0.282, y, z0, cx + 0.282, y + 0.018, z1);
        }
      }
      const r = rng(3);
      for (let i = 0; i < 14; i++) {
        const t = (i + 0.5) / 14;
        const key = i % 3 ? 'linen' : 'fabricAccent';
        if (dir === 'x') {
          const z = z0 + t * (z1 - z0);
          if (kind !== 'standard' && Math.abs(z - (z0 + z1) / 2) < 0.32) continue;
          gr.box(key, x0 + 0.07, 0.94 + r() * 0.1, z, x1 - 0.07, 1.63, z + 0.032);
        } else {
          const x = x0 + t * (x1 - x0);
          if (kind !== 'standard' && Math.abs(x - (x0 + x1) / 2) < 0.32) continue;
          gr.box(key, x, 0.94 + r() * 0.1, z0 + 0.07, x + 0.032, 1.63, z1 - 0.07);
        }
      }
    }
  }

  return { buildDoors, buildRobes };
}
