// Generated by splitting the original interior.js — geometry is unchanged.
import { Mesh, MeshBuilder } from '../babylon.js';
import { roundedBox, lathe, tube, cylinder, sphere, place } from '../interiorParts.js';
import { CEIL, K, BENCH_H, BENCH_D, KICK_H, KICK_IN, OVER_Y0, OVER_Y1, OVER_D } from './layout.js';

export function createKitchen(ctx) {
  const { scene, IM, S, makeGroup, cabinetRun, benchTop, sinkRect, sinkAt, mixerAt, handleAt } = ctx;

  // =================================================================
  // KITCHEN + WALK-IN PANTRY + STORAGE (Ground Floor Plan)
  // =================================================================
  function buildKitchen() {
    const g = makeGroup('kitchen');
    const profile = S['k-cabinets']?.profile;
    const hOpt = S['k-handles']?.handle;
    const stoneT = S['k-benchtop']?.style?.thick ?? 0.02;
    const waterfall = !!S['k-benchtop']?.style?.waterfall;
    const oh = S['k-cabinets']?.overheads?.kind || 'full';
    const rh = S['k-cooking']?.rangehood;
    const setup = S['k-cooking']?.setup?.id;

    // ---- back bench (cooktop run) between the two nib walls
    cabinetRun(g, 'kCab', { x0: K.wall, x1: K.benchFront, z0: K.benchZ0, z1: K.benchZ1, face: 'x+', profile, handle: hOpt, drawers: true });
    g.box('kStone', K.wall, BENCH_H, K.benchZ0, K.benchFront + 0.02, BENCH_H + stoneT, K.benchZ1);
    g.box('splash', K.wall, BENCH_H + stoneT, K.benchZ0, K.wall + 0.016, 1.05, K.benchZ1);

    // ---- walk-in pantry bench, standard 1 3/4 bowl sink under the window
    cabinetRun(g, 'kCab', { x0: K.wall, x1: K.benchFront, z0: K.pantryZ0, z1: K.pantryZ1, face: 'x+', profile, handle: hOpt });
    const pSink = { bowls: 1.75, mount: 'inset', mat: 'stainless' };
    benchTop(g, 'kStone', K.wall, BENCH_H, K.pantryZ0, K.benchFront + 0.02, BENCH_H + stoneT, K.pantryZ1,
      sinkRect(pSink, K.pantrySink.x, K.pantrySink.z, 'x'));
    g.box('splash', K.wall, BENCH_H + stoneT, K.pantryZ0, K.wall + 0.016, 1.05, K.pantryZ1);
    sinkAt(g, K.pantrySink.x, K.pantrySink.z, pSink, stoneT, 'x');
    mixerAt(g, K.wall + 0.11, K.pantrySink.z, { shape: 'gooseneck' }, BENCH_H + stoneT, 'x');

    // ---- island 3237 x 1000 with a 400 breakfast overhang
    const iz0 = K.islandZ0;
    const iz1 = K.islandZ1;
    cabinetRun(g, 'kIsland', { x0: K.islandX0, x1: K.islandX1, z0: iz0, z1: iz0 + BENCH_D, face: 'z-', profile, handle: hOpt, drawers: true });
    g.box('kIsland', K.islandX0, KICK_H, iz0 + BENCH_D, K.islandX1, BENCH_H, iz0 + BENCH_D + 0.02); // panelled back
    const kSink = S['k-sink']?.sink || { bowls: 1.75, mount: 'inset', mat: 'stainless' };
    benchTop(g, 'kStone', K.islandX0 - (waterfall ? 0.022 : 0.012), BENCH_H, iz0 - 0.022,
      K.islandX1 + (waterfall ? 0.022 : 0.012), BENCH_H + stoneT, iz1,
      sinkRect(kSink, K.sink.x, K.sink.z, 'z'));
    if (waterfall) {
      g.box('kStone', K.islandX0 - 0.022, 0.012, iz0 - 0.022, K.islandX0, BENCH_H + stoneT, iz1);
      g.box('kStone', K.islandX1, 0.012, iz0 - 0.022, K.islandX1 + 0.022, BENCH_H + stoneT, iz1);
    }
    sinkAt(g, K.sink.x, K.sink.z, kSink, stoneT, 'z');
    mixerAt(g, K.sink.x, K.sink.z + 0.30, S['k-sink']?.mixer || {}, BENCH_H + stoneT, 'z');
    const dw = S['k-appliances']?.dishwasher;
    if (dw && dw.kind !== 'none') {
      const dx0 = K.sink.x + 0.46;
      const key = `${dw.kind === 'integrated' ? 'kIsland' : dw.kind === 'black' ? 'appBlack' : 'appSS'}#k-appliances`;
      g.box(key, dx0, KICK_H, iz0 - 0.02, dx0 + 0.6, BENCH_H - 0.02, iz0 + 0.02);
      if (dw.kind !== 'integrated') g.box('handle#k-appliances', dx0 + 0.05, BENCH_H - 0.14, iz0 - 0.055, dx0 + 0.55, BENCH_H - 0.1, iz0 - 0.03);
      else if (hOpt) handleAt(g, 'x', dx0 + 0.3, BENCH_H - 0.14, 'z-', dx0, dx0 + 0.6, iz0 - 0.02, iz0 + 0.02, hOpt, 0.25);
    }

    // ---- tall run: pantry cupboards -> oven tower -> fridge
    const TALL_Y = 2.45;
    cabinetRun(g, 'kCab', { x0: K.colX1 - 2.157, x1: K.colX1, z0: K.colZ0, z1: K.colZ1, y1: TALL_Y, face: 'z+', profile, handle: hOpt });
    ovenTower(g, TALL_Y, profile, hOpt, setup);
    fridge(g, TALL_Y, profile, hOpt);

    // ---- overhead cupboards over the bench, either side of the window
    if (oh !== 'none') {
      const segs = [[K.benchZ0, K.winKitchen[0] - 0.03], [K.winKitchen[1] + 0.03, K.benchZ1]];
      for (const [a, b] of segs) {
        if (b - a < 0.2) continue;
        if (oh === 'open') {
          for (const y of [1.78, 2.14]) g.box('oak', K.wall, y, a, K.wall + OVER_D, y + 0.035, b);
        } else {
          cabinetRun(g, 'kOver', {
            x0: K.wall, x1: K.wall + OVER_D, z0: a, z1: b, y0: OVER_Y0, y1: OVER_Y1,
            face: 'x+', profile, handle: hOpt, unit: oh === 'two' ? (b - a) / 2 : 0.5,
          });
        }
      }
      if (oh !== 'open' && rh?.kind !== 'canopy') {
        cabinetRun(g, 'kOver', {
          x0: K.wall, x1: K.wall + OVER_D, z0: K.winKitchen[0] - 0.03, z1: K.winKitchen[1] + 0.03,
          y0: 1.72, y1: OVER_Y1, face: 'x+', profile, handle: hOpt,
        });
      }
      g.box('ceil', K.wall, OVER_Y1, K.benchZ0, K.wall + OVER_D, CEIL, K.benchZ1); // bulkhead
    }

    // ---- cooking
    const cz = K.cooktopZ;
    if (setup === 'cs-freestanding') {
      const w = 0.9;
      g.box('cooker', K.wall + 0.02, 0.02, cz - w / 2, K.wall + 0.66, 0.92, cz + w / 2);
      g.box('appGlass', K.wall + 0.03, 0.26, cz - w / 2 + 0.06, K.wall + 0.05, 0.76, cz + w / 2 - 0.06);
      g.box('appSS', K.wall + 0.02, 0.9, cz - w / 2, K.wall + 0.64, 0.93, cz + w / 2);
      for (let i = 0; i < 5; i++) g.box('handle', K.wall + 0.02, 0.84, cz - 0.38 + i * 0.19, K.wall + 0.05, 0.88, cz - 0.31 + i * 0.19);
      g.box('appSS', K.wall - 0.02, 0.79, cz - w / 2 + 0.04, K.wall + 0.02, 0.83, cz + w / 2 - 0.04);
      for (const zz of [-0.3, -0.1, 0.1, 0.3]) {
        g.add(cylinder(scene, 0.03, 0.15, 0.17, { x: K.wall + 0.3, y: 0.945, z: cz + zz }), 'appBlack');
      }
    } else if (S['k-cooking']?.cooktop) {
      const ct = S['k-cooking'].cooktop;
      const w = ct.w || 0.6;
      g.box('appGlass', K.wall + 0.06, BENCH_H + stoneT, cz - w / 2, K.wall + 0.58, BENCH_H + stoneT + 0.007, cz + w / 2);
      if (ct.kind === 'gas') {
        for (const zz of [-0.32, -0.11, 0.11, 0.32]) {
          const bx = K.wall + (Math.abs(zz) > 0.2 ? 0.2 : 0.4);
          const bz = cz + zz * (w / 0.9);
          g.box('appSS', bx - 0.09, BENCH_H + stoneT + 0.006, bz - 0.09, bx + 0.09, BENCH_H + stoneT + 0.018, bz + 0.09);
          g.add(cylinder(scene, 0.028, 0.1, 0.13, { x: bx, y: BENCH_H + stoneT + 0.03, z: bz }), 'appBlack');
        }
      }
    }
    if (rh) {
      const w = rh.w || 0.6;
      if (rh.kind === 'canopy') {
        g.box(rh.dark ? 'appBlack' : 'appSS', K.wall + 0.02, 1.72, cz - w / 2, K.wall + 0.54, 1.85, cz + w / 2);
        g.box(rh.dark ? 'appBlack' : 'appSS', K.wall + 0.02, 1.85, cz - 0.14, K.wall + 0.28, CEIL, cz + 0.14);
      } else if (rh.kind === 'slideout') {
        g.box('appSS', K.wall + 0.02, 1.62, cz - w / 2, K.wall + 0.34, 1.72, cz + w / 2);
        g.box('appSS', K.wall + 0.34, 1.64, cz - w / 2, K.wall + 0.46, 1.69, cz + w / 2);
      } else {
        g.box('appSS', K.wall + 0.03, 1.66, cz - w / 2, K.wall + 0.32, 1.73, cz + w / 2);
      }
    }

    // ---- walk-in pantry L-shelving + storage room shelves
    for (let y = 0.42; y <= 1.95; y += 0.5) {
      g.box('mel', K.pantryDiv - 0.5, y, K.pantryZ0, K.pantryDiv, y + 0.024, K.pantryZ1);
      g.box('mel', -3.84, y, K.pantryZ0, K.pantryDiv - 0.5, y + 0.024, K.pantryZ0 + 0.5);
    }
    g.box('mel', K.pantryDiv - 0.5, BENCH_H, K.pantryZ0, K.pantryDiv, BENCH_H + 0.03, K.pantryZ1);
    for (let y = 0.45; y <= 1.95; y += 0.48) {
      g.box('mel', K.storageX[0], y, K.storageZ[0] + 0.05, K.storageX[0] + 0.4, y + 0.024, K.storageZ[1] - 0.05);
    }

    // ---- stools + pendants
    for (const sx of [-1.25, -2.15, -3.05]) stool(g, sx, iz1 + 0.35);
    for (const sx of [-1.35, -2.3, -3.25]) pendant(g, sx, (iz0 + iz1) / 2 - 0.05);

    g.finish();
  }

  function ovenTower(g, TALL_Y, profile, hOpt, setup) {
    const [x0, x1] = K.ovenX;
    const z0 = K.colZ0;
    const z1 = K.colZ1;
    g.box('kCab', x0, KICK_H, z0, x1, TALL_Y, z1);
    g.box('kick', x0, 0.012, z0, x1, KICK_H, z1 - KICK_IN);
    const oven = S['k-cooking']?.oven;
    const mw = S['k-appliances']?.microwave;
    let y = 0.86;
    if (setup !== 'cs-freestanding' && oven) {
      const h = oven.w >= 0.9 ? 0.5 : 0.6;
      g.box(oven.face === 'stainless' ? 'appSS' : 'appBlack', x0 + 0.012, y, z1 - 0.012, x1 - 0.012, y + h, z1 + 0.018);
      g.box('appGlass', x0 + 0.055, y + 0.1, z1 + 0.018, x1 - 0.055, y + h - 0.1, z1 + 0.026);
      g.box('handle', x0 + 0.04, y + h - 0.075, z1 + 0.018, x1 - 0.04, y + h - 0.04, z1 + 0.055);
      y += h + 0.02;
    }
    if (mw?.kind === 'builtin') {
      g.box('appSS#k-appliances', x0 + 0.012, y, z1 - 0.012, x1 - 0.012, y + 0.42, z1 + 0.016);
      g.box('appGlass#k-appliances', x0 + 0.05, y + 0.06, z1 + 0.016, x1 - 0.17, y + 0.34, z1 + 0.022);
      y += 0.44;
    }
    cabinetRun(g, 'kCab', { x0, x1, z0, z1, y0: Math.max(y, 1.6), y1: TALL_Y, face: 'z+', profile, handle: hOpt });
  }

  function fridge(g, TALL_Y, profile, hOpt) {
    const [x0, x1] = K.fridgeX;
    const z0 = K.colZ0;
    const z1 = K.colZ1;
    const fr = S['k-appliances']?.fridge;
    if (fr?.kind === 'integrated') {
      cabinetRun(g, 'kCab', { x0, x1, z0, z1, y0: 0, y1: TALL_Y, face: 'z+', profile, handle: hOpt, unit: (x1 - x0) / 2 });
      return;
    }
    const mid = (x0 + x1) / 2;
    g.box('appSS#k-appliances', x0 + 0.02, 0.02, z0 + 0.02, x1 - 0.02, 1.86, z1 + 0.12);
    g.box('appBlack#k-appliances', x0 + 0.03, 0.04, z1 + 0.12, x1 - 0.03, 1.18, z1 + 0.15); // freezer drawer
    g.box('appBlack#k-appliances', x0 + 0.03, 1.21, z1 + 0.12, mid - 0.006, 1.84, z1 + 0.15);
    g.box('appBlack#k-appliances', mid + 0.006, 1.21, z1 + 0.12, x1 - 0.03, 1.84, z1 + 0.15);
    g.box('handle#k-appliances', mid - 0.09, 1.32, z1 + 0.15, mid - 0.068, 1.76, z1 + 0.19);
    g.box('handle#k-appliances', mid + 0.068, 1.32, z1 + 0.15, mid + 0.09, 1.76, z1 + 0.19);
    g.box('handle#k-appliances', x0 + 0.12, 0.86, z1 + 0.15, x0 + 0.142, 1.1, z1 + 0.19);
    cabinetRun(g, 'kCab', { x0, x1, z0, z1, y0: 1.92, y1: TALL_Y, face: 'z+', profile, handle: hOpt, unit: (x1 - x0) / 2 });
  }

  function stool(g, x, z) {
    const seat = roundedBox(scene, 0.36, 0.07, 0.34, 0.03, 4);
    place(seat, x, 0.665, z);
    g.add(seat, 'oak');
    for (const [dx, dz] of [[-0.14, -0.13], [0.14, -0.13], [-0.14, 0.13], [0.14, 0.13]]) {
      g.add(cylinder(scene, 0.63, 0.024, 0.03, { x: x + dx, y: 0.315, z: z + dz }), 'blackMetal');
    }
    const ring = MeshBuilder.CreateTorus('stool-ring', { diameter: 0.31, thickness: 0.016, tessellation: 14 }, scene);
    place(ring, x, 0.22, z);
    g.add(ring, 'blackMetal');
  }

  function pendant(g, x, z) {
    g.add(place(cylinder(scene, 0.86, 0.008, 0.008), x, CEIL - 0.44, z), 'blackMetal');
    g.add(place(cylinder(scene, 0.02, 0.09, 0.09), x, CEIL - 0.012, z), 'blackMetal');
    const shade = lathe(scene, [[0.004, 0.24], [0.075, 0.15], [0.115, 0.02], [0.118, 0.0]], { tess: 22 });
    place(shade, x, 1.7, z);
    g.add(shade, 'blackMetal');
    g.add(sphere(scene, 0.09, { x, y: 1.73, z }), 'led');
  }

  return { buildKitchen };
}
