// Generated by splitting the original interior.js — geometry is unchanged.
import { MeshBuilder } from '../babylon.js';
import { roundedBox, lathe, tube, cylinder, sphere, place } from '../interiorParts.js';
import { CEIL, ENS, BATH, WC, LDRY, VANITY, BENCH_H, BENCH_D } from './layout.js';

export function createBath(ctx) {
  const { scene, IM, S, makeGroup, cabinetRun, benchTop, mixerAt, lin } = ctx;

  // =================================================================
  // ENSUITE, MAIN BATHROOM, WC
  // =================================================================
  function buildBath() {
    const g = makeGroup('bath');
    const stoneT = S['b-benchtop']?.edge?.thick ?? 0.02;
    const acc = S['b-accessories'];

    // --- Ensuite: vanity on the laundry wall, shower + toilet on the outer wall
    vanity(g, { x0: 2.86, x1: 4.06, zWall: ENS.z1, dir: -1, stoneT });
    shower(g, { x0: 4.22, x1: ENS.x1, z0: -5.12, z1: ENS.z1 - 0.02, head: S['b-shower']?.ensuite });
    toiletAt(g, ENS.x1, -5.62, -1, S['b-toilet']);
    towelRail(g, 'x', 2.45, ENS.z1, -1, acc);
    // walk-in robe shelving on the hallway side of the ensuite zone
    for (let y = 0.5; y <= 1.95; y += 0.46) g.box('mel', ENS.x0, y, -5.93, ENS.x0 + 0.55, y + 0.024, -4.62);
    g.box('handle', ENS.x0 + 0.26, 1.70, -5.93, ENS.x0 + 0.288, 1.728, -4.62);

    // --- Main bathroom (1500 x 2890): 1500 bath along the outer wall, 1500 x 900
    //     shower beside the linen, and the vanity out in the passage, per the plan.
    bathTub(g, S['b-bath']?.bath, 4.335, BATH.z0 + 0.05, S['b-bath']?.tap, { axis: 'z', w: 0.88, max: 1.44 });
    shower(g, { x0: BATH.x0, x1: 3.29, z0: BATH.z0 + 0.02, z1: BATH.z1 - 0.02, head: S['b-shower']?.main, face: 1 });
    towelRail(g, 'x', 3.78, BATH.z0, +1, acc);

    // --- Vanity bench in the passage, against the Bed 3 wall
    vanity(g, { x0: VANITY.x0, x1: VANITY.x1, zWall: VANITY.zWall, dir: -1, stoneT });

    // --- Separate WC: pan against the Bed 3 wall
    toiletAt(g, WC.z1, 4.83, -1, S['b-toilet'], 'z');
    g.box('acc', WC.x1 - 0.13, 0.72, 7.94, WC.x1 - 0.02, 0.79, 8.02); // roll holder

    // --- Linen cupboard shelves (between the shower and the hall)
    for (let y = 0.45; y <= 2.0; y += 0.42) g.box('mel', 1.79, y, 5.35, 2.29, y + 0.022, 6.76);

    g.finish();
  }

  function vanity(g, { x0, x1, zWall, dir, stoneT }) {
    const v = S['b-vanity'];
    const style = v?.style?.style || 'wall';
    const d = 0.46;
    const z0 = dir < 0 ? zWall - d : zWall;
    const z1 = dir < 0 ? zWall : zWall + d;
    const y0 = style === 'wall' || style === 'drawers' ? 0.36 : 0.0;
    const top = 0.85;
    cabinetRun(g, 'vCab', {
      x0, x1, z0, z1, y0, y1: top, face: dir < 0 ? 'z-' : 'z+',
      profile: v?.profile, handle: v?.handle, drawers: style === 'drawers', unit: (x1 - x0) / 2,
    });
    if (style === 'shelf') {
      const cx = (x0 + x1) / 2;
      g.box('vCab', cx - 0.22, 0.0, z0, cx + 0.22, top, z1 - 0.1);
      for (const yy of [0.32, 0.56]) g.box('oak', cx - 0.2, yy, z0 + 0.02, cx + 0.2, yy + 0.022, z1 - 0.12);
    }
    const bx = (x0 + x1) / 2;
    const bz = (z0 + z1) / 2;
    const basin = S['b-basin']?.basin;
    const inset = (basin?.mount || 'inset') !== 'above';
    benchTop(g, 'vStone', x0 - 0.012, top, z0, x1 + 0.012, top + stoneT, z1,
      inset ? [bx - 0.23, bz - 0.185, bx + 0.23, bz + 0.185] : null);
    basinAt(g, bx, bz, top + stoneT, basin);
    const tapType = S['b-basin']?.tapType;
    if (tapType?.mount === 'wall') {
      const zt = dir < 0 ? zWall - 0.012 : zWall + 0.012;
      g.box('tap', bx - 0.075, 1.09, Math.min(zt, zt + dir * 0.035), bx + 0.075, 1.155, Math.max(zt, zt + dir * 0.035));
      g.add(place(cylinder(scene, 0.17, 0.026, 0.028, { rot: [Math.PI / 2, 0, 0] }), bx, 1.122, zt + dir * 0.085), 'tap');
    } else {
      mixerAt(g, bx, bz - dir * 0.165, { shape: S['b-basin']?.range?.style === 'square' ? 'square' : 'gooseneck' }, top + stoneT, 'z');
    }
    // mirror
    const mw = Math.min(x1 - x0, 1.2);
    const shape = S['b-accessories']?.mirror?.shape || 'rect';
    const zm = dir < 0 ? zWall - 0.018 : zWall + 0.018;
    if (shape === 'round' || shape === 'arch') {
      const disc = MeshBuilder.CreateCylinder('mirror-disc', { height: 0.02, diameter: Math.min(0.78, mw), tessellation: 32 }, scene);
      disc.rotation.x = Math.PI / 2;
      place(disc, bx, shape === 'arch' ? 1.62 : 1.5, zm);
      g.add(disc, 'mirror');
      if (shape === 'arch') g.box('mirror', bx - Math.min(0.39, mw / 2), 1.08, zm - 0.008, bx + Math.min(0.39, mw / 2), 1.62, zm + 0.008);
    } else {
      const r = shape === 'curved' ? 0.06 : 0;
      g.box('mirror', bx - mw / 2 + r, 1.05, zm - 0.008, bx + mw / 2 - r, 1.95, zm + 0.008);
      if (r) g.box('mirror', bx - mw / 2, 1.05 + r, zm - 0.008, bx + mw / 2, 1.95 - r, zm + 0.008);
    }
  }

  function basinAt(g, x, z, y, basin) {
    const shape = basin?.shape || 'round';
    const mount = basin?.mount || 'inset';
    IM.basin.albedoColor = lin(basin?.colour || basin?.hex || '#ffffff');
    if (mount === 'above') {
      const prof = shape === 'oval' || shape === 'pill'
        ? [[0.0, 0.135], [0.2, 0.135], [0.21, 0.115], [0.185, 0.0], [0.0, 0.0]]
        : [[0.0, 0.125], [0.18, 0.125], [0.19, 0.105], [0.165, 0.0], [0.0, 0.0]];
      const m = lathe(scene, prof, { tess: 28, sx: shape === 'oval' || shape === 'pill' ? 1.4 : 1 });
      place(m, x, y, z);
      g.add(m, 'basin');
      g.add(place(cylinder(scene, 0.016, 0.045, 0.045), x, y + 0.012, z), 'tap');
    } else {
      const m = lathe(scene, [[0.0, 0.0], [0.195, 0.0], [0.2, -0.02], [0.17, -0.14], [0.0, -0.15]], {
        tess: 28, sx: shape === 'square' ? 1.18 : 1.25,
      });
      place(m, x, y + 0.002, z);
      g.add(m, 'basin');
      if (shape === 'square') g.box('basin', x - 0.235, y - 0.006, z - 0.19, x + 0.235, y + 0.006, z + 0.19);
      g.add(place(cylinder(scene, 0.016, 0.045, 0.045), x, y - 0.138, z), 'tap');
    }
  }

  // face -1: the screen is on the x0 side; face +1: on the x1 side (fittings go on
  // the opposite, tiled wall).
  function shower(g, { x0, x1, z0, z1, head, face = -1 }) {
    const kind = head?.kind || 'single';
    const sx = face < 0 ? x0 : x1;        // screen plane
    const wx = face < 0 ? x1 : x0;        // wall side
    const o = (d) => sx + face * d;
    g.box('wetTile', x0, 0.031, z0, x1, 0.041, z1); // tiled shower floor
    // semi-frameless screen: fixed panel + return, door gap left open
    g.box('screenFrame', o(0), 0.03, z0, o(0.022), 2.0, z1);
    g.box('screenGlass', o(0.006), 0.04, z0 + 0.02, o(0.014), 1.98, z1 - 0.62);
    g.box('screenFrame', o(0), 0.03, z1 - 0.65, o(0.022), 2.0, z1 - 0.61);
    g.box('screenGlass', o(0.014), 0.04, z0 + 0.02, wx + face * 0.02, 1.98, z0 + 0.028);
    const cx = (x0 + x1) / 2;
    const zr = z0 + 0.42;
    if (kind === 'ceiling') {
      g.add(place(cylinder(scene, 0.3, 0.022, 0.022), cx, CEIL - 0.16, (z0 + z1) / 2), 'shower');
      g.add(place(cylinder(scene, 0.02, 0.23, 0.23, { tess: 24 }), cx, CEIL - 0.31, (z0 + z1) / 2), 'shower');
    } else {
      const w = (d) => wx - face * d; // inward from the tiled wall
      g.box('shower', w(0.115), 0.95, zr, w(0.085), 1.96, zr + 0.032); // slide rail
      g.add(place(cylinder(scene, 0.03, 0.1, 0.1, { rot: [0, 0, Math.PI / 2] }), w(0.1), 1.56, zr + 0.06), 'shower');
      g.add(place(cylinder(scene, 0.11, 0.028, 0.028, { rot: [0, 0, Math.PI / 2.6] }), w(0.16), 1.5, zr + 0.06), 'shower');
      if (kind === 'twin') {
        g.box('shower', w(0.115), 1.96, zr, w(0.055), 2.01, zr + 0.032);
        g.add(place(cylinder(scene, 0.016, 0.2, 0.2, { tess: 20, rot: [0.22, 0, 0] }), w(0.34), 1.99, zr + 0.03), 'shower');
      }
      g.add(place(cylinder(scene, 0.045, 0.085, 0.085, { rot: [0, 0, Math.PI / 2] }), w(0.022), 1.1, zr + 0.4), 'shower'); // mixer
    }
    g.box('shower', cx - 0.05, 0.038, (z0 + z1) / 2 - 0.05, cx + 0.05, 0.044, (z0 + z1) / 2 + 0.05); // floor waste
  }

  // The tub fills an alcove: `axis` is the direction its length runs, (x0, z0) is
  // the alcove corner it starts from, and the tap end is at that corner.
  function bathTub(g, bath, x0, z0, tap, { axis = 'x', w = 0.74, max = 1.5 } = {}) {
    const kind = bath?.kind || 'free';
    const len = Math.min(bath?.len || 1.6, max);
    IM.bath.albedoColor = lin(bath?.colour || '#ffffff');
    const alongX = axis === 'x';
    const dx = alongX ? len : w;
    const dz = alongX ? w : len;
    const cx = x0 + dx / 2;
    const cz = z0 + dz / 2;
    const prof = [[0.0, 0.0], [0.46, 0.0], [0.5, 0.05], [0.5, 0.55], [0.47, 0.58], [0.44, 0.55], [0.42, 0.1], [0.0, 0.08]];
    const m = lathe(scene, prof, { tess: 30, sx: dx, sz: dz });
    place(m, cx, 0.02, cz);
    g.add(m, 'bath');
    // head end (taps) at the (x0, z0) corner, foot end opposite
    const head = alongX ? [x0, cz] : [cx, z0];
    const foot = alongX ? [x0 + len, cz] : [cx, z0 + len];
    if (kind === 'btw') {
      if (alongX) g.box('bath', x0, 0.02, cz - dz / 2 - 0.06, x0 + len, 0.6, cz - dz / 2 + 0.04);
      else g.box('bath', cx - dx / 2 - 0.06, 0.02, z0, cx - dx / 2 + 0.04, 0.6, z0 + len);
    }
    if (tap?.mount === 'floor') {
      const fx = alongX ? head[0] - 0.16 : head[0] + 0.42;
      const fz = alongX ? head[1] + 0.42 : head[1] - 0.16;
      g.add(place(cylinder(scene, 0.86, 0.03, 0.05), fx, 0.43, fz), 'tap');
      g.add(tube(scene, alongX
        ? [[fx, 0.86, fz], [fx + 0.06, 0.95, fz], [fx + 0.20, 0.93, fz]]
        : [[fx, 0.86, fz], [fx, 0.95, fz + 0.06], [fx, 0.93, fz + 0.20]], 0.019, 10), 'tap');
    } else if (alongX) {
      g.box('tap', head[0] - 0.06, 0.76, head[1] - 0.07, head[0] - 0.045, 0.83, head[1] + 0.07);
      g.add(place(cylinder(scene, 0.19, 0.025, 0.025, { rot: [0, 0, Math.PI / 2] }), head[0] + 0.05, 0.795, head[1]), 'tap');
    } else {
      g.box('tap', head[0] - 0.07, 0.76, head[1] - 0.06, head[0] + 0.07, 0.83, head[1] - 0.045);
      g.add(place(cylinder(scene, 0.19, 0.025, 0.025, { rot: [Math.PI / 2, 0, 0] }), head[0], 0.795, head[1] + 0.05), 'tap');
    }
    if (alongX) g.box('towel', foot[0] - 0.30, 0.3, foot[1] - 0.36, foot[0] - 0.04, 0.62, foot[1] - 0.2);
    else g.box('towel', foot[0] - 0.36, 0.3, foot[1] - 0.30, foot[0] - 0.2, 0.62, foot[1] - 0.04);
  }

  // The suite backs onto a wall: `axis` is the wall's constant axis, `wallPos` its
  // face, `at` the position along it and `dir` points into the room.
  function toiletAt(g, wallPos, at, dir, sel, axis = 'x') {
    const kind = sel?.suite?.kind || 'coupled';
    const alongX = axis === 'x';
    const back = wallPos + dir * 0.01;
    // local (depth from the wall, offset along the wall) -> world
    const W = (d, a = 0) => (alongX ? [back + dir * d, at + a] : [at + a, back + dir * d]);
    const put = (key, d0, y0, a0, d1, y1, a1) => {
      const p = W(d0, a0);
      const q = W(d1, a1);
      g.box(key, p[0], y0, p[1], q[0], y1, q[1]);
    };
    const pan = lathe(scene, [[0.0, 0.0], [0.14, 0.02], [0.16, 0.2], [0.185, 0.38], [0.2, 0.4], [0.0, 0.4]],
      { tess: 22, sx: alongX ? 1 : 1.35, sz: alongX ? 1.35 : 1 });
    const pc = W(0.33);
    place(pan, pc[0], 0.0, pc[1]);
    g.add(pan, 'porcelain');
    const seat = roundedBox(scene, alongX ? 0.4 : 0.5, 0.035, alongX ? 0.5 : 0.4, 0.016, 3);
    place(seat, pc[0], 0.425, pc[1]);
    g.add(seat, 'porcelain');
    const lc = W(0.13);
    const lid = roundedBox(scene, alongX ? 0.12 : 0.46, 0.03, alongX ? 0.46 : 0.12, 0.014, 3);
    place(lid, lc[0], 0.45, lc[1]);
    g.add(lid, 'porcelain');
    if (kind === 'inwall') {
      put('porcelain', 0, 0.0, -0.3, 0.2, 1.1, 0.3); // duct wall
      put('acc', 0.2, 0.9, -0.11, 0.215, 1.05, 0.11); // flush plate
    } else {
      put('porcelain', 0, 0.4, -0.2, 0.22, 0.82, 0.2); // cistern
      const bc = W(0.11);
      g.add(place(cylinder(scene, 0.02, 0.07, 0.07), bc[0], 0.83, bc[1]), 'acc');
    }
  }

  function towelRail(g, axis, at, wallPos, dir, acc) {
    const style = acc?.range?.style || 'round';
    const put = (a, b, y0, y1, o0, o1) => {
      const d0 = Math.min(wallPos + dir * o0, wallPos + dir * o1);
      const d1 = Math.max(wallPos + dir * o0, wallPos + dir * o1);
      if (axis === 'x') g.box('acc', a, y0, d0, b, y1, d1);
      else g.box('acc', d0, y0, a, d1, y1, b);
    };
    const towel = (a, b, y0, y1) => {
      const d0 = Math.min(wallPos + dir * 0.02, wallPos + dir * 0.075);
      const d1 = Math.max(wallPos + dir * 0.02, wallPos + dir * 0.075);
      if (axis === 'x') g.box('towel', a, y0, d0, b, y1, d1);
      else g.box('towel', d0, y0, a, d1, y1, b);
    };
    if (style === 'ladder') {
      put(at - 0.28, at - 0.25, 0.9, 1.66, 0.005, 0.04);
      put(at + 0.25, at + 0.28, 0.9, 1.66, 0.005, 0.04);
      for (let y = 0.98; y < 1.66; y += 0.17) put(at - 0.28, at + 0.28, y, y + 0.022, 0.01, 0.055);
      towel(at - 0.2, at + 0.04, 0.98, 1.44);
    } else {
      put(at - 0.3, at + 0.3, 1.19, 1.215, 0.02, 0.055);
      put(at - 0.3, at + 0.3, 1.13, 1.155, 0.04, 0.075);
      put(at - 0.3, at - 0.27, 1.13, 1.22, 0.005, 0.075);
      put(at + 0.27, at + 0.3, 1.13, 1.22, 0.005, 0.075);
      towel(at - 0.24, at - 0.04, 0.83, 1.205);
      towel(at + 0.04, at + 0.24, 0.83, 1.205);
    }
  }

  // =================================================================
  // LAUNDRY
  // =================================================================
  function buildLaundry() {
    const g = makeGroup('laundry');
    const sel = S.laundry;
    const stone = sel?.bench?.top === 'stone';
    const v = S['b-vanity'];
    const z0 = LDRY.z0;
    const z1 = LDRY.z0 + BENCH_D;
    const topY = BENCH_H + (stone ? 0.02 : 0.033);
    cabinetRun(g, 'lCab', { x0: 2.0, x1: 2.76, z0, z1, face: 'z+', profile: v?.profile, handle: v?.handle, unit: 0.38 });
    g.box(stone ? 'lStone' : 'lCab', 1.98, BENCH_H, z0, 2.78, topY, z1 + 0.02);
    // stainless drop-in tub
    g.box('tub', 2.12, topY - 0.22, z0 + 0.1, 2.64, topY - 0.2, z1 - 0.06);
    g.box('tub', 2.12, topY - 0.22, z0 + 0.1, 2.14, topY, z1 - 0.06);
    g.box('tub', 2.62, topY - 0.22, z0 + 0.1, 2.64, topY, z1 - 0.06);
    g.box('tub', 2.12, topY - 0.22, z0 + 0.1, 2.64, topY, z0 + 0.12);
    g.box('tub', 2.12, topY - 0.22, z1 - 0.08, 2.64, topY, z1 - 0.06);
    mixerAt(g, 2.38, z0 + 0.13, { shape: 'gooseneck' }, topY, 'z');
    // washer + dryer under the bench return
    for (const x of [2.95, 3.65]) {
      g.box('appSS', x, 0.02, z0 + 0.04, x + 0.6, 0.86, z0 + 0.64);
      g.add(place(cylinder(scene, 0.04, 0.34, 0.34, { rot: [Math.PI / 2, 0, 0] }), x + 0.3, 0.5, z0 + 0.02), 'appGlass');
      g.box('appSS', x + 0.02, 0.72, z0, x + 0.58, 0.82, z0 + 0.04);
    }
    g.box(stone ? 'lStone' : 'lCab', 2.9, 0.86, z0 + 0.02, 4.32, 0.9, z1 + 0.02);
    const extras = sel?.extras?.extras;
    if (extras === 'overhead') {
      cabinetRun(g, 'lCab', { x0: 2.0, x1: 4.32, z0, z1: z0 + 0.35, y0: 1.55, y1: 2.15, face: 'z+', profile: v?.profile, handle: v?.handle });
    } else if (extras === 'shelves') {
      for (const y of [1.55, 1.9]) g.box('oak', 2.0, y, z0, 4.32, y + 0.035, z0 + 0.3);
    }
    // broom cupboard against the media wall
    cabinetRun(g, 'lCab', { x0: 4.62, x1: 5.22, z0: LDRY.z1 - 0.62, z1: LDRY.z1, y0: 0, y1: 2.25, face: 'z-', profile: v?.profile, handle: v?.handle, unit: 0.6 });
    g.finish();
  }

  return { buildBath, vanity, shower, bathTub, toiletAt, towelRail, buildLaundry };
}
