// Generated by splitting the original interior.js — geometry is unchanged.
import { roundedBox, lathe, tube, cylinder, sphere, place } from '../interiorParts.js';
import { BENCH_H, KICK_H, KICK_IN } from './layout.js';

export function createCabinets(ctx) {
  const { scene, IM, S, lin } = ctx;

  // =================================================================
  // CABINETRY PRIMITIVES
  // =================================================================
  function cabinetRun(g, key, { x0, x1, z0, z1, y0 = 0, y1 = BENCH_H, face, profile, handle: hOpt, drawers = false, unit = 0.6 }) {
    const base = y0 + (y0 === 0 ? KICK_H : 0);
    g.box(key, x0, base, z0, x1, y1, z1);
    if (y0 === 0) {
      const kx0 = face === 'x-' ? x0 + KICK_IN : x0;
      const kx1 = face === 'x+' ? x1 - KICK_IN : x1;
      const kz0 = face === 'z-' ? z0 + KICK_IN : z0;
      const kz1 = face === 'z+' ? z1 - KICK_IN : z1;
      g.box('kick', kx0, 0.012, kz0, kx1, KICK_H, kz1);
    }
    const along = face === 'z-' || face === 'z+' ? 'x' : 'z';
    const s0 = along === 'x' ? x0 : z0;
    const s1 = along === 'x' ? x1 : z1;
    const n = Math.max(1, Math.round((s1 - s0) / unit));
    const rows = drawers ? (S['k-cabinets']?.drawers?.layout === 'bank' ? 4 : 3) : 1;
    for (let i = 0; i < n; i++) {
      const a = s0 + ((s1 - s0) * i) / n + 0.004;
      const b = s0 + ((s1 - s0) * (i + 1)) / n - 0.004;
      for (let r = 0; r < rows; r++) {
        const v0 = base + ((y1 - base) * r) / rows + 0.004;
        const v1 = base + ((y1 - base) * (r + 1)) / rows - 0.004;
        front(g, key, along, a, b, v0, v1, face, x0, x1, z0, z1, profile);
        if (hOpt) {
          const hy = drawers ? (v0 + v1) / 2 : Math.min(v1 - 0.1, base + 0.75);
          handleAt(g, along, (a + b) / 2, hy, face, x0, x1, z0, z1, hOpt, drawers ? (b - a) * 0.45 : 0);
        }
      }
    }
  }

  function front(g, key, along, a, b, v0, v1, face, x0, x1, z0, z1, profile) {
    const fd = 0.018;
    const out = face === 'z-' ? [z0 - fd, z0] : face === 'z+' ? [z1, z1 + fd] : face === 'x-' ? [x0 - fd, x0] : [x1, x1 + fd];
    const outward = face === 'z-' || face === 'x-' ? -1 : 1;
    const put = (aa, bb, w0, w1, d0, d1) => {
      if (along === 'x') g.box(key, aa, w0, d0, bb, w1, d1);
      else g.box(key, d0, w0, aa, d1, w1, bb);
    };
    put(a, b, v0, v1, out[0], out[1]);
    const p = profile?.profile;
    const facePlane = outward > 0 ? out[1] : out[0];
    if (p === 'shaker' || p === 'settler' || p === 'square') {
      const inset = p === 'settler' ? 0.055 : 0.075;
      const d = p === 'square' ? 0.004 : 0.007;
      if (b - a > inset * 2.4 && v1 - v0 > inset * 2.4) {
        put(a + inset, b - inset, v0 + inset, v1 - inset, facePlane, facePlane + outward * d);
      }
    } else if (p === 'vgroove') {
      for (let u = a + 0.05; u < b - 0.03; u += 0.068) {
        put(u, u + 0.009, v0 + 0.012, v1 - 0.012, facePlane, facePlane + outward * 0.005);
      }
    }
  }

  function handleAt(g, along, at, y, face, x0, x1, z0, z1, hOpt, span = 0) {
    const shape = hOpt.shape || 'bar';
    const outward = face === 'z-' || face === 'x-' ? -1 : 1;
    const base = face === 'z-' ? z0 - 0.019 : face === 'z+' ? z1 + 0.019 : face === 'x-' ? x0 - 0.019 : x1 + 0.019;
    const D = (d) => base + outward * d;
    const put = (u0, u1, v0, v1, d0, d1) => {
      if (along === 'x') g.box('handle', u0, v0, d0, u1, v1, d1);
      else g.box('handle', d0, v0, u0, d1, v1, u1);
    };
    if (shape === 'finger') {
      put(at - Math.max(0.16, span), at + Math.max(0.16, span), y + 0.02, y + 0.052, D(0), D(0.012));
      return;
    }
    if (shape === 'knob') {
      put(at - 0.007, at + 0.007, y - 0.007, y + 0.007, D(0), D(0.022));
      put(at - 0.018, at + 0.018, y - 0.018, y + 0.018, D(0.022), D(0.042));
      return;
    }
    const half = Math.max(hOpt.len || 0.12, span) / 2;
    if (shape === 'cup' || shape === 'bow') {
      put(at - half, at + half, y - 0.013, y + 0.013, D(0.018), D(0.032));
      put(at - half, at - half + 0.018, y - 0.022, y + 0.022, D(0), D(0.02));
      put(at + half - 0.018, at + half, y - 0.022, y + 0.022, D(0), D(0.02));
    } else {
      put(at - half, at + half, y - 0.009, y + 0.009, D(0.022), D(0.04));
      put(at - half, at - half + 0.016, y - 0.008, y + 0.008, D(0), D(0.024));
      put(at + half - 0.016, at + half, y - 0.008, y + 0.008, D(0), D(0.024));
    }
  }

  // Benchtop with the sink/basin cut-out left open.
  function benchTop(g, key, x0, y0, z0, x1, y1, z1, hole) {
    if (!hole) {
      g.box(key, x0, y0, z0, x1, y1, z1);
      return;
    }
    const [hx0, hz0, hx1, hz1] = hole;
    const put = (a, b, c, d) => {
      if (b - a > 0.004 && d - c > 0.004) g.box(key, a, y0, c, b, y1, d);
    };
    put(x0, x1, z0, Math.max(z0, hz0));
    put(x0, x1, Math.min(z1, hz1), z1);
    put(x0, Math.max(x0, hx0), Math.max(z0, hz0), Math.min(z1, hz1));
    put(Math.min(x1, hx1), x1, Math.max(z0, hz0), Math.min(z1, hz1));
  }

  // Footprint of a sink, so the benchtop can be cut around it.
  function sinkRect(sink, x, z, axis = 'z') {
    const bowls = sink.bowls || 1;
    const long = sink.w || (bowls >= 1.75 ? 0.82 : 0.5);
    const w = axis === 'x' ? 0.42 : long;
    const d = axis === 'x' ? long : 0.42;
    return [x - w / 2, z - d / 2, x + w / 2, z + d / 2];
  }

  // Sink cut into a benchtop. axis 'z' -> bowls run along X, 'x' -> along Z.
  function sinkAt(g, x, z, sink, stoneT, axis = 'z') {
    const y = BENCH_H + stoneT;
    const bowls = sink.bowls || 1;
    const long = sink.w || (bowls >= 1.75 ? 0.82 : 0.5);
    const w = axis === 'x' ? 0.42 : long;
    const d = axis === 'x' ? long : 0.42;
    const mat = sink.mat === 'ceramic' || sink.mat === 'granite-white' ? 'porcelain' : sink.mat === 'granite-black' ? 'appBlack' : 'sink';
    const depth = 0.19;
    const t = 0.012;
    const x0 = x - w / 2;
    const x1 = x + w / 2;
    const z0 = z - d / 2;
    const z1 = z + d / 2;
    if (sink.mount === 'over' || sink.mount === 'inset') {
      const r = sink.mount === 'over' ? 0.016 : 0.008;
      g.box(mat, x0 - r, y, z0 - r, x1 + r, y + 0.007, z0 + 0.004);
      g.box(mat, x0 - r, y, z1 - 0.004, x1 + r, y + 0.007, z1 + r);
      g.box(mat, x0 - r, y, z0 - r, x0 + 0.004, y + 0.007, z1 + r);
      g.box(mat, x1 - 0.004, y, z0 - r, x1 + r, y + 0.007, z1 + r);
    }
    g.box(mat, x0, y - depth, z0, x1, y - depth + t, z1);
    g.box(mat, x0, y - depth, z0, x0 + t, y, z1);
    g.box(mat, x1 - t, y - depth, z0, x1, y, z1);
    g.box(mat, x0, y - depth, z0, x1, y, z0 + t);
    g.box(mat, x0, y - depth, z1 - t, x1, y, z1);
    if (bowls >= 2) {
      if (axis === 'z') g.box(mat, x - t / 2, y - depth, z0, x + t / 2, y, z1);
      else g.box(mat, x0, y - depth, z - t / 2, x1, y, z + t / 2);
    } else if (bowls === 1.75) {
      if (axis === 'z') g.box(mat, x1 - 0.24 - t / 2, y - depth * 0.55, z0, x1 - 0.24 + t / 2, y, z1);
      else g.box(mat, x0, y - depth * 0.55, z1 - 0.24 - t / 2, x1, y, z1 - 0.24 + t / 2);
    }
    if (sink.mount === 'farmhouse' || sink.mount === 'butler') {
      if (axis === 'z') g.box(mat, x0 - 0.02, y - 0.44, z0 - 0.03, x1 + 0.02, y, z0 + 0.02);
      else g.box(mat, x0 - 0.03, y - 0.44, z0 - 0.02, x0 + 0.02, y, z1 + 0.02);
    }
    g.add(place(cylinder(scene, 0.02, 0.09, 0.09), x, y - depth + 0.02, z), mat === 'sink' ? 'sink' : 'mixer');
  }

  function mixerAt(g, x, z, mixer, y, axis = 'x') {
    const shape = mixer.shape || 'gooseneck';
    g.add(place(cylinder(scene, 0.03, 0.055, 0.06), x, y + 0.015, z), 'mixer');
    const dx = axis === 'x' ? 1 : 0;
    const dz = axis === 'x' ? 0 : 1;
    if (shape === 'spring' || shape === 'pullout') {
      g.add(place(cylinder(scene, 0.34, 0.032, 0.034), x, y + 0.2, z), 'mixer');
      g.add(tube(scene, [
        [x, y + 0.37, z],
        [x + dx * 0.05, y + 0.43, z + dz * 0.05],
        [x + dx * 0.13, y + 0.41, z + dz * 0.13],
      ], 0.017, 10), 'mixer');
      g.add(place(cylinder(scene, 0.1, 0.038, 0.042), x + dx * 0.13, y + 0.34, z + dz * 0.13), 'mixer');
    } else {
      const pts = [];
      for (let i = 0; i <= 12; i++) {
        const t = i / 12;
        const bend = Math.max(0, (t - 0.5) / 0.5) ** 1.5 * 0.17;
        pts.push([x + dx * bend, y + 0.05 + t * 0.32 - bend * 0.3, z + dz * bend]);
      }
      g.add(tube(scene, pts, shape === 'square' ? 0.019 : 0.016, 10), 'mixer');
      const lev = cylinder(scene, 0.09, 0.015, 0.017, { rot: [dz ? Math.PI / 2.3 : 0, 0, dx ? Math.PI / 2.3 : 0] });
      g.add(place(lev, x - dx * 0.04, y + 0.13, z - dz * 0.04), 'mixer');
    }
  }

  return { cabinetRun, handleAt, benchTop, sinkRect, sinkAt, mixerAt };
}
