// Generated by splitting the original interior.js — geometry is unchanged.
import { CEIL, MEDIA } from './layout.js';

export function createCeilings(ctx) {
  const { house, S, makeGroup } = ctx;

  // =================================================================
  // CEILINGS: media bulkhead with LED cove + downlights
  // =================================================================
  function buildCeilings() {
    const g = makeGroup('ceilings');
    const b = 0.42;
    const { x0, x1, z0, z1 } = MEDIA;
    g.box('ceil', x0, CEIL - 0.3, z0, x1, CEIL, z0 + b);
    g.box('ceil', x0, CEIL - 0.3, z1 - b, x1, CEIL, z1);
    g.box('ceil', x0, CEIL - 0.3, z0 + b, x0 + b, CEIL, z1 - b);
    g.box('ceil', x1 - b, CEIL - 0.3, z0 + b, x1, CEIL, z1 - b);
    const ly = CEIL - 0.265;
    g.box('led', x0 + b, ly, z0 + b, x1 - b, ly + 0.025, z0 + b + 0.02);
    g.box('led', x0 + b, ly, z1 - b - 0.02, x1 - b, ly + 0.025, z1 - b);
    g.box('led', x0 + b, ly, z0 + b, x0 + b + 0.02, ly + 0.025, z1 - b);
    g.box('led', x1 - b - 0.02, ly, z0 + b, x1 - b, ly + 0.025, z1 - b);

    const spots = [];
    for (let z = 1.7; z <= 8.0; z += 1.55) for (const x of [-4.7, -2.7, -0.7]) spots.push([x, z]);
    spots.push([-4.9, -0.5], [-4.9, 0.7], [-2.0, -0.6], [-4.9, -2.7], [-1.1, -2.7]);
    for (let z = -8.6; z <= -4.2; z += 1.45) spots.push([0.9, z]);
    for (const p of [[3.5, -7.8], [3.5, -5.1], [3.5, -3.1], [3.5, 3.6], [3.5, 5.9], [3.5, 7.3], [3.5, 9.8], [-1.0, 10.2], [1.2, 9.4]]) spots.push(p);
    for (const [x, z] of spots) {
      g.box('ceil', x - 0.055, CEIL - 0.012, z - 0.055, x + 0.055, CEIL - 0.004, z + 0.055);
      g.box('led', x - 0.042, CEIL - 0.016, z - 0.042, x + 0.042, CEIL - 0.01, z + 0.042);
    }
    g.finish();
  }

  // =================================================================
  // WINDOW FURNISHINGS
  // =================================================================
  function buildWindowFurnishings() {
    const g = makeGroup('winfurn');
    const kind = S['window-furnishings']?.type?.kind;
    if (!kind) {
      g.finish();
      return;
    }
    for (const w of house.plan.windows) {
      if (w.frosted || w.room === 'pantry' || w.room === 'kitchen') continue;
      if (w.y1 - w.y0 < 0.9 || w.s1 - w.s0 < 0.5) continue;
      // wall-local box: s along the wall, d negative = into the room
      const box = (key, s0, s1, y0, y1, d0, d1) => {
        const p = w.wall.world(s0, y0, d0);
        const q = w.wall.world(s1, y1, d1);
        g.box(key, p[0], p[1], p[2], q[0], q[1], q[2]);
      };
      if (kind === 'shutter') {
        const d0 = -0.055;
        const d1 = -0.078;
        box('shutter', w.s0 - 0.03, w.s1 + 0.03, w.y1, w.y1 + 0.04, d0, d1);
        box('shutter', w.s0 - 0.03, w.s1 + 0.03, w.y0 - 0.04, w.y0, d0, d1);
        const panels = Math.max(2, Math.round((w.s1 - w.s0) / 0.55));
        for (let i = 0; i <= panels; i++) {
          const s = w.s0 + ((w.s1 - w.s0) * i) / panels;
          box('shutter', s - 0.022, s + 0.022, w.y0, w.y1, d0, d1);
        }
        for (let i = 0; i < panels; i++) {
          const a = w.s0 + ((w.s1 - w.s0) * i) / panels + 0.024;
          const b = w.s0 + ((w.s1 - w.s0) * (i + 1)) / panels - 0.024;
          for (let y = w.y0 + 0.03; y < w.y1 - 0.05; y += 0.076) box('shutter', a, b, y, y + 0.058, d0 - 0.002, d0 - 0.014);
        }
      } else if (kind === 'roller') {
        const drop = 0.4;
        box('blind', w.s0 - 0.02, w.s1 + 0.02, w.y1 - (w.y1 - w.y0) * drop, w.y1 + 0.02, -0.05, -0.062);
        box('woodwork', w.s0 - 0.04, w.s1 + 0.04, w.y1 + 0.02, w.y1 + 0.09, -0.042, -0.072);
      } else {
        const yTop = Math.min(CEIL - 0.06, Math.max(w.y1 + 0.22, 2.46));
        box('woodwork', w.s0 - 0.36, w.s1 + 0.36, yTop, yTop + 0.045, -0.085, -0.135);
        for (const side of [-1, 1]) {
          const base = side < 0 ? w.s0 - 0.32 : w.s1 - 0.08;
          for (let i = 0; i < 6; i++) {
            const s = base + i * 0.07;
            const dd = -0.085 - (i % 2) * 0.05;
            box('curtain', s, s + 0.055, 0.03, yTop - 0.012, dd, dd - 0.055);
          }
        }
      }
    }
    g.finish();
  }

  return { buildCeilings, buildWindowFurnishings };
}
