// Generated by splitting the original interior.js — geometry is unchanged.
import { Mesh, MeshBuilder } from '../babylon.js';
import { roundedBox, lathe, tube, cylinder, sphere, place } from '../interiorParts.js';
import { rng } from '../textures.js';
import { CEIL, K, MEDIA } from './layout.js';

export function createFurniture(ctx) {
  const { scene, IM, makeGroup } = ctx;

  // =================================================================
  // FURNITURE
  // =================================================================
  function buildFurniture() {
    const g = makeGroup('furniture');

    // ---- family room
    rug(g, -5.25, 3.15, -1.85, 6.55);
    sofa(g, -2.55, 4.85, 2.5, 0.96, 1); // faces -X toward the TV wall
    coffeeTable(g, -3.85, 4.85);
    tvUnit(g, K.wall, 4.85);
    plant(g, -5.2, 7.75, 1.0);
    floorLamp(g, -5.15, 3.05);
    art(g, 1.695, 1.72, 6.45, 1.15, 0.85, -1);

    // ---- dining
    diningTable(g, -1.15, 6.45, 1.0, 1.9);
    for (let i = 0; i < 3; i++) {
      chair(g, -1.72, 5.7 + i * 0.75, 'x+');
      chair(g, -0.58, 5.7 + i * 0.75, 'x-');
    }
    pendantBar(g, -1.15, 6.45);

    // ---- media room
    rug(g, 2.25, -1.45, 4.85, 1.35);
    sofa(g, 2.8, -0.05, 2.4, 0.96, -1); // faces +X toward the screen
    g.box('oakDark', MEDIA.x1 - 0.44, 0.08, -0.9, MEDIA.x1 - 0.06, 0.52, 0.9);
    g.box('handle', MEDIA.x1 - 0.47, 0.3, -0.62, MEDIA.x1 - 0.44, 0.33, -0.18);
    g.box('handle', MEDIA.x1 - 0.47, 0.3, 0.18, MEDIA.x1 - 0.44, 0.33, 0.62);
    g.box('tv', MEDIA.x1 - 0.075, 0.95, -0.8, MEDIA.x1 - 0.04, 1.72, 0.8);

    // ---- bedrooms
    bed(g, { hx: 1.83, hz: -8.33, dir: '+x', w: 1.83, bounds: [1.785, -9.305, 5.23, -6.10] }); // master
    bed(g, { hx: 3.65, hz: 2.23, dir: '+z', bounds: [2.36, 2.19, 5.23, 5.10] }); // bed 2
    bed(g, { hx: 3.40, hz: 11.545, dir: '-z', bounds: [1.785, 8.09, 5.23, 11.585] }); // bed 3
    bed(g, { hx: -1.55, hz: 10.50, dir: '+x', bounds: [-1.60, 9.20, 1.695, 11.60] }); // bed 4

    // ---- entry console
    g.box('oak', 0.28, 0.7, -8.6, 0.6, 0.75, -7.6);
    for (const z of [-8.52, -7.72]) {
      g.box('blackMetal', 0.33, 0.02, z, 0.37, 0.7, z + 0.04);
      g.box('blackMetal', 0.52, 0.02, z, 0.56, 0.7, z + 0.04);
    }
    g.add(place(sphere(scene, 0.2, { sy: 1.2 }), 0.44, 0.84, -8.05), 'pot');
    art(g, 0.045, 1.6, -8.1, 0.9, 0.7, +1);

    // ---- alfresco setting
    diningTable(g, -4.15, 10.15, 0.95, 1.6, 'oakDark');
    for (const dz of [-0.5, 0.5]) {
      chair(g, -4.62, 10.15 + dz, 'x+', 'oakDark');
      chair(g, -3.68, 10.15 + dz, 'x-', 'oakDark');
    }
    g.box('appSS', -5.42, 0.08, 8.8, -4.82, 0.92, 9.45); // BBQ
    g.box('appBlack', -5.44, 0.6, 8.78, -4.8, 0.7, 9.47);
    g.box('handle', -5.47, 0.72, 8.85, -5.44, 0.76, 9.4);

    g.finish();
  }

  function rug(g, x0, z0, x1, z1) {
    g.box('rug', x0, 0.032, z0, x1, 0.048, z1);
  }

  // dir +1 -> the sofa faces -X (back at +X); dir -1 -> faces +X
  function sofa(g, x, z, len, depth, dir) {
    const seatH = 0.42;
    const base = roundedBox(scene, depth, seatH, len, 0.05, 4);
    place(base, x, seatH / 2 + 0.06, z);
    g.add(base, 'fabricSofa');
    const back = roundedBox(scene, 0.24, 0.58, len, 0.07, 4);
    place(back, x + dir * (depth / 2 - 0.12), seatH + 0.3, z);
    g.add(back, 'fabricSofa');
    for (const s of [-1, 1]) {
      const arm = roundedBox(scene, depth, 0.3, 0.24, 0.07, 4);
      place(arm, x, seatH + 0.17, z + s * (len / 2 - 0.12));
      g.add(arm, 'fabricSofa');
    }
    const n = Math.max(2, Math.round(len / 0.92));
    for (let i = 0; i < n; i++) {
      const cz = z - len / 2 + (len / n) * (i + 0.5);
      const cus = roundedBox(scene, depth - 0.3, 0.15, len / n - 0.08, 0.05, 4);
      place(cus, x - dir * 0.07, seatH + 0.13, cz);
      g.add(cus, 'fabricSofa');
      const pil = roundedBox(scene, 0.13, 0.36, 0.36, 0.06, 4);
      place(pil, x + dir * (depth / 2 - 0.27), seatH + 0.36, cz + 0.12);
      pil.rotation.z = -dir * 0.2;
      g.add(pil, i % 2 ? 'fabricAccent' : 'linen');
    }
    for (const sx of [-1, 1]) {
      for (const sz of [-1, 1]) {
        g.add(cylinder(scene, 0.12, 0.028, 0.034, { x: x + sx * (depth / 2 - 0.12), y: 0.06, z: z + sz * (len / 2 - 0.16) }), 'oakDark');
      }
    }
  }

  function coffeeTable(g, x, z) {
    const top = roundedBox(scene, 0.64, 0.05, 1.15, 0.02, 3);
    place(top, x, 0.42, z);
    g.add(top, 'oak');
    for (const [dx, dz] of [[-0.25, -0.47], [0.25, -0.47], [-0.25, 0.47], [0.25, 0.47]]) {
      g.add(cylinder(scene, 0.4, 0.028, 0.028, { x: x + dx, y: 0.2, z: z + dz }), 'blackMetal');
    }
    g.add(place(lathe(scene, [[0, 0], [0.085, 0.02], [0.095, 0.12], [0.055, 0.2], [0.05, 0.22]], { tess: 18 }), x, 0.445, z - 0.22), 'pot');
    g.box('book', x - 0.16, 0.445, z + 0.12, x + 0.16, 0.487, z + 0.38);
    g.box('linen', x - 0.15, 0.487, z + 0.14, x + 0.15, 0.515, z + 0.36);
  }

  function tvUnit(g, xWall, z) {
    g.box('oakDark', xWall, 0.12, z - 0.95, xWall + 0.44, 0.54, z + 0.95);
    g.box('handle', xWall + 0.44, 0.3, z - 0.66, xWall + 0.47, 0.33, z - 0.24);
    g.box('handle', xWall + 0.44, 0.3, z + 0.24, xWall + 0.47, 0.33, z + 0.66);
    g.box('tv', xWall + 0.04, 0.98, z - 0.75, xWall + 0.09, 1.76, z + 0.75);
    g.box('blackMetal', xWall + 0.05, 0.54, z - 0.05, xWall + 0.12, 0.98, z + 0.05);
  }

  function diningTable(g, x, z, w = 1.0, d = 1.9, mat = 'oak') {
    g.box(mat, x - w / 2, 0.72, z - d / 2, x + w / 2, 0.765, z + d / 2);
    g.box(mat, x - w / 2 + 0.06, 0.66, z - d / 2 + 0.06, x + w / 2 - 0.06, 0.72, z + d / 2 - 0.06);
    for (const dx of [-w / 2 + 0.12, w / 2 - 0.12]) {
      for (const dz of [-d / 2 + 0.12, d / 2 - 0.12]) {
        g.box('blackMetal', x + dx - 0.028, 0.02, z + dz - 0.028, x + dx + 0.028, 0.66, z + dz + 0.028);
      }
    }
    g.add(place(lathe(scene, [[0, 0], [0.07, 0.01], [0.08, 0.1], [0.05, 0.16], [0.045, 0.18]], { tess: 16 }), x, 0.765, z), 'pot');
    g.add(sphere(scene, 0.17, { x, y: 0.94, z, sy: 0.9 }), 'leaf');
  }

  // facing 'x+' -> the chair's back is at -X (it looks toward +X)
  function chair(g, x, z, facing, mat = 'oak') {
    const dir = facing === 'x+' ? -1 : 1;
    const seat = roundedBox(scene, 0.46, 0.07, 0.44, 0.025, 3);
    place(seat, x, 0.45, z);
    g.add(seat, mat === 'oak' ? 'fabricSofa' : mat);
    const back = roundedBox(scene, 0.07, 0.46, 0.42, 0.03, 3);
    place(back, x + dir * 0.2, 0.72, z);
    back.rotation.z = -dir * 0.08;
    g.add(back, mat === 'oak' ? 'fabricSofa' : mat);
    for (const dx of [-0.18, 0.18]) {
      for (const dz of [-0.17, 0.17]) {
        g.add(cylinder(scene, 0.45, 0.022, 0.028, { x: x + dx, y: 0.225, z: z + dz }), mat === 'oak' ? 'oakDark' : 'blackMetal');
      }
    }
  }

  function pendantBar(g, x, z) {
    g.box('blackMetal', x - 0.045, CEIL - 0.055, z - 0.5, x + 0.045, CEIL - 0.015, z + 0.5);
    for (const dz of [-0.36, 0, 0.36]) {
      g.add(place(cylinder(scene, 0.55, 0.006, 0.006), x, CEIL - 0.33, z + dz), 'blackMetal');
      const sh = lathe(scene, [[0.004, 0.17], [0.07, 0.11], [0.1, 0.0]], { tess: 18 });
      place(sh, x, 1.88, z + dz);
      g.add(sh, 'brass');
      g.add(sphere(scene, 0.07, { x, y: 1.89, z: z + dz }), 'led');
    }
  }

  // Bed built in local coordinates: u across, v from the headboard into the room.
  function bed(g, { hx, hz, dir, w = 1.6, len = 2.05, bounds }) {
    const ax = dir === '+x' || dir === '-x';
    const map = (u, v) => (
      dir === '+x' ? [hx + v, hz + u]
        : dir === '-x' ? [hx - v, hz - u]
          : dir === '+z' ? [hx - u, hz + v] : [hx + u, hz - v]);
    const lbox = (key, u0, y0, v0, u1, y1, v1) => {
      const a = map(u0, v0);
      const b = map(u1, v1);
      g.box(key, a[0], y0, a[1], b[0], y1, b[1]);
    };
    const size = (across, along) => (ax ? [along, across] : [across, along]);
    lbox('oakDark', -w / 2, 0.07, 0.06, w / 2, 0.32, len); // base
    const [mw, md] = size(w - 0.05, len - 0.06);
    const mat = roundedBox(scene, mw, 0.26, md, 0.04, 4);
    const mc = map(0, len / 2 + 0.03);
    place(mat, mc[0], 0.45, mc[1]);
    g.add(mat, 'linen');
    const [dwid, ddep] = size(w + 0.06, len - 0.62);
    const doona = roundedBox(scene, dwid, 0.13, ddep, 0.05, 4);
    const dc = map(0, (0.62 + len) / 2);
    place(doona, dc[0], 0.585, dc[1]);
    g.add(doona, 'fabricSofa');
    for (const s of [-1, 1]) {
      const [pw, pd] = size(w * 0.42, 0.35);
      const p = roundedBox(scene, pw, 0.14, pd, 0.06, 4);
      const pc = map(s * w * 0.24, 0.3);
      place(p, pc[0], 0.63, pc[1]);
      p.rotation[ax ? 'z' : 'x'] = 0.14;
      g.add(p, 'linen');
    }
    lbox('fabricSofa', -w / 2 - 0.08, 0.1, -0.1, w / 2 + 0.08, 1.06, 0.02); // headboard
    // bedside tables, skipped where the room runs out
    for (const s of [-1, 1]) {
      const u = s * (w / 2 + 0.24);
      const c = map(u, 0.24);
      if (bounds && (c[0] < bounds[0] + 0.24 || c[0] > bounds[2] - 0.24 || c[1] < bounds[1] + 0.24 || c[1] > bounds[3] - 0.24)) continue;
      lbox('oak', u - 0.22, 0.07, 0.02, u + 0.22, 0.5, 0.46);
      lbox('handle', u - 0.07, 0.3, -0.008, u + 0.07, 0.33, 0.02);
      g.add(place(cylinder(scene, 0.025, 0.14, 0.14), c[0], 0.52, c[1]), 'brass');
      g.add(place(cylinder(scene, 0.2, 0.018, 0.018), c[0], 0.62, c[1]), 'brass');
      const shade = lathe(scene, [[0.004, 0.19], [0.1, 0.19], [0.13, 0.0]], { tess: 18 });
      place(shade, c[0], 0.7, c[1]);
      g.add(shade, 'linen');
    }
  }

  function plant(g, x, z, s = 1) {
    const pot = lathe(scene, [[0, 0], [0.19, 0.02], [0.21, 0.32], [0.18, 0.34], [0.165, 0.32], [0.175, 0.04], [0, 0.03]], { tess: 20 });
    place(pot, x, 0.02, z);
    pot.scaling.setAll(s);
    g.add(pot, 'pot');
    const r = rng(9);
    for (let i = 0; i < 16; i++) {
      const h = (0.35 + r() * 0.85) * s;
      const ang = r() * Math.PI * 2;
      const leaf = MeshBuilder.CreatePlane('leaf', { width: 0.17 * s, height: 0.3 * s, sideOrientation: Mesh.DOUBLESIDE }, scene);
      leaf.position.set(x + Math.cos(ang) * 0.14 * s, 0.36 * s + h, z + Math.sin(ang) * 0.14 * s);
      leaf.rotation.set(r() * 0.7 - 0.35, ang, r() * 0.5 - 0.25);
      g.add(leaf, 'leaf');
      g.add(cylinder(scene, h, 0.011 * s, 0.015 * s, {
        x: x + Math.cos(ang) * 0.05 * s, y: 0.34 * s + h / 2, z: z + Math.sin(ang) * 0.05 * s,
      }), 'leaf');
    }
  }

  function floorLamp(g, x, z) {
    g.add(place(cylinder(scene, 0.03, 0.3, 0.3), x, 0.035, z), 'blackMetal');
    g.add(place(cylinder(scene, 1.45, 0.022, 0.022), x, 0.78, z), 'blackMetal');
    const shade = lathe(scene, [[0.004, 0.25], [0.14, 0.22], [0.17, 0.0]], { tess: 18 });
    place(shade, x, 1.5, z);
    g.add(shade, 'linen');
    g.add(sphere(scene, 0.1, { x, y: 1.6, z }), 'led');
  }

  // Framed art on a wall plane at x = xWall, facing `dir`.
  function art(g, xWall, y, z, w, h, dir) {
    const a = xWall;
    const b = xWall + dir * 0.035;
    g.box('oakDark', Math.min(a, b), y - h / 2, z - w / 2, Math.max(a, b), y + h / 2, z + w / 2);
    const c = xWall + dir * 0.036;
    const d = xWall + dir * 0.042;
    g.box('art', Math.min(c, d), y - h / 2 + 0.05, z - w / 2 + 0.05, Math.max(c, d), y + h / 2 - 0.05, z + w / 2 - 0.05);
  }

  return { buildFurniture };
}
