// Generated by splitting the original interior.js — geometry is unchanged.
import { CEIL, K, WALL_LINES, EXTRA_GAPS } from './layout.js';

export function createTrims(ctx) {
  const { house, S, makeGroup } = ctx;

  // =================================================================
  // TRIMS: skirting, cornice, feature wall
  // =================================================================
  // Break a wall line where a door or floor-level opening crosses it.
  function runs(axis, pos, a, b) {
    const gaps = [];
    for (const op of house.plan.openings) {
      if (op.axis === axis && Math.abs(op.pos - pos) < 0.12) gaps.push([op.a - 0.035, op.b + 0.035]);
    }
    for (const w of house.plan.windows) {
      if (w.y0 > 0.12) continue;
      const p = w.wall.world(w.s0, 0, 0);
      const q = w.wall.world(w.s1, 0, 0);
      const along = Math.abs(q[0] - p[0]) > Math.abs(q[2] - p[2]) ? 'x' : 'z';
      if (along !== axis) continue;
      const fixed = axis === 'x' ? 2 : 0; // the wall's constant coordinate
      if (Math.abs(p[fixed] - pos) > 0.3) continue;
      const j = axis === 'x' ? 0 : 2;
      gaps.push([Math.min(p[j], q[j]) - 0.02, Math.max(p[j], q[j]) + 0.02]);
    }
    for (const g of EXTRA_GAPS) if (g[0] === axis && Math.abs(g[1] - pos) < 0.3) gaps.push([g[2], g[3]]);
    let segs = [[a, b]];
    for (const [ga, gb] of gaps) {
      const next = [];
      for (const [s0, s1] of segs) {
        if (gb <= s0 || ga >= s1) next.push([s0, s1]);
        else {
          if (ga > s0) next.push([s0, ga]);
          if (gb < s1) next.push([gb, s1]);
        }
      }
      segs = next;
    }
    return segs;
  }

  // A thin face applied to a wall line, `depth` out from the wall face.
  function faceBox(g, key, axis, pos, s0, s1, y0, y1, side, depth) {
    if (depth <= 0 || s1 - s0 <= 0) return;
    if (axis === 'z') g.box(key, pos, y0, s0, pos + side * depth, y1, s1);
    else g.box(key, s0, y0, pos, s1, y1, pos + side * depth);
  }

  // Every opening that crosses a wall line, as [s0, s1, y0, y1] in line coordinates.
  function holesOn(axis, pos) {
    const holes = [];
    for (const op of house.plan.openings) {
      if (op.axis === axis && Math.abs(op.pos - pos) < 0.12) holes.push([op.a - 0.02, op.b + 0.02, 0, 2.40]);
    }
    for (const w of house.plan.windows) {
      const p = w.wall.world(w.s0, 0, 0);
      const q = w.wall.world(w.s1, 0, 0);
      const along = Math.abs(q[0] - p[0]) > Math.abs(q[2] - p[2]) ? 'x' : 'z';
      if (along !== axis) continue;
      const fixed = axis === 'x' ? 2 : 0;
      if (Math.abs(p[fixed] - pos) > 0.3) continue;
      const j = axis === 'x' ? 0 : 2;
      holes.push([Math.min(p[j], q[j]), Math.max(p[j], q[j]), w.y0, w.y1]);
    }
    for (const g of EXTRA_GAPS) if (g[0] === axis && Math.abs(g[1] - pos) < 0.3) holes.push([g[2], g[3], 0, 2.40]);
    return holes;
  }

  // Split a wall face into the solid cells left between its openings.
  function cells(a, b, y0, y1, holes) {
    const S1 = [...new Set([a, b, ...holes.flatMap((h) => [h[0], h[1]]).filter((v) => v > a && v < b)])].sort((p, q) => p - q);
    const Y1 = [...new Set([y0, y1, ...holes.flatMap((h) => [h[2], h[3]]).filter((v) => v > y0 && v < y1)])].sort((p, q) => p - q);
    const out = [];
    for (let i = 0; i < S1.length - 1; i++) {
      let start = null;
      for (let j = 0; j < Y1.length - 1; j++) {
        const cs = (S1[i] + S1[i + 1]) / 2;
        const cy = (Y1[j] + Y1[j + 1]) / 2;
        const solid = !holes.some((h) => cs > h[0] && cs < h[1] && cy > h[2] && cy < h[3]);
        if (solid && start === null) start = Y1[j];
        if ((!solid || j === Y1.length - 2) && start !== null) {
          out.push([S1[i], S1[i + 1], start, solid ? Y1[j + 1] : Y1[j]]);
          start = null;
        }
      }
    }
    return out;
  }

  // Plasterboard lining on the inside face of the brick exterior walls.
  function buildLining() {
    const g = makeGroup('lining');
    for (const [axis, pos, a, b, side, kind] of WALL_LINES) {
      if (kind !== 'ext') continue;
      const holes = holesOn(axis, pos);
      for (const [s0, s1, y0, y1] of cells(a, b, 0.0, CEIL, holes)) {
        if (s1 - s0 < 0.02 || y1 - y0 < 0.02) continue;
        faceBox(g, 'wall', axis, pos, s0, s1, y0, y1, side, 0.012);
      }
    }
    g.finish();
  }

  function buildTrims() {
    const g = makeGroup('trims');
    const skirt = S.trims?.skirting;
    const corn = S.trims?.cornice;
    const sh = 0.092; // 92mm skirting
    const st = 0.018;
    const cs = corn?.size ?? 0.075;
    const steps = corn?.profile === 'step' || corn?.profile === 'newyork' ? 3 : corn?.profile === 'manly' ? 2 : 4;
    for (const [axis, pos, a, b, side] of WALL_LINES) {
      for (const [s0, s1] of runs(axis, pos, a, b)) {
        if (s1 - s0 < 0.12) continue;
        faceBox(g, 'woodwork', axis, pos, s0, s1, 0.012, sh, side, st);
        if (skirt?.profile === 'round') faceBox(g, 'woodwork', axis, pos, s0, s1, sh, sh + 0.008, side, st - 0.006);
        else if (skirt?.profile === 'bevel') faceBox(g, 'woodwork', axis, pos, s0, s1, sh - 0.024, sh, side, st - 0.008);
        else faceBox(g, 'woodwork', axis, pos, s0, s1, sh - 0.014, sh, side, st - 0.005); // half splayed
      }
      if (cs > 0) {
        for (let i = 0; i < steps; i++) {
          const d = cs * (1 - (i + 0.5) / steps) + 0.006;
          faceBox(g, 'ceil', axis, pos, a, b, CEIL - (cs * (i + 1)) / steps, CEIL - (cs * i) / steps, side, d);
        }
      }
    }
    // feature wall - family room TV wall, between the two side windows
    const kind = S.feature?.type?.id;
    const z0 = 3.05;
    const z1 = 6.35;
    if (kind === 'fw-hardigroove') {
      for (let z = z0; z < z1 - 0.01; z += 0.133) {
        g.box('feature', K.wall, 0.10, z, K.wall + 0.022, CEIL - 0.08, Math.min(z1, z + 0.115));
      }
    } else if (kind === 'fw-dado') {
      g.box('feature', K.wall, 0.10, z0, K.wall + 0.018, 1.05, z1);
      g.box('feature', K.wall, 1.05, z0, K.wall + 0.038, 1.105, z1); // dado rail
      for (let z = z0 + 0.1; z < z1 - 0.5; z += 0.62) {
        g.box('feature', K.wall + 0.018, 0.2, z, K.wall + 0.03, 0.96, Math.min(z1 - 0.1, z + 0.5));
      }
    }
    g.finish();
  }

  return { runs, faceBox, buildLining, buildTrims };
}
